python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs1.7/twi_pairs/twi_pairs.py --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs1.7/twi_pairs
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs1.7/twi_pairs/twi_pairs.py --repeat_night --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs1.7/twi_pairs
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs1.7/twi_pairs/twi_pairs_mixed.py --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs1.7/twi_pairs
python /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs1.7/twi_pairs/twi_pairs_mixed.py --repeat_night --outDir /gscratch/astro/yoachim/git_repos/sims_featureScheduler_runs1.7/twi_pairs
