python /gscratch/scrubbed/yoachim/sims_featureScheduler_runs1.7/pair_times/pair_times.py --pair_time 11 --outDir /gscratch/scrubbed/yoachim/sims_featureScheduler_runs1.7/pair_times
python /gscratch/scrubbed/yoachim/sims_featureScheduler_runs1.7/pair_times/pair_times.py --pair_time 22 --outDir /gscratch/scrubbed/yoachim/sims_featureScheduler_runs1.7/pair_times
python /gscratch/scrubbed/yoachim/sims_featureScheduler_runs1.7/pair_times/pair_times.py --pair_time 33 --outDir /gscratch/scrubbed/yoachim/sims_featureScheduler_runs1.7/pair_times
python /gscratch/scrubbed/yoachim/sims_featureScheduler_runs1.7/pair_times/pair_times.py --pair_time 44 --outDir /gscratch/scrubbed/yoachim/sims_featureScheduler_runs1.7/pair_times
python /gscratch/scrubbed/yoachim/sims_featureScheduler_runs1.7/pair_times/pair_times.py --pair_time 55 --outDir /gscratch/scrubbed/yoachim/sims_featureScheduler_runs1.7/pair_times
