python /gscratch/scrubbed/yoachim/sims_featureScheduler_runs1.7/twi_neo/twilight_neo.py --night_pattern 1 --outDir /gscratch/scrubbed/yoachim/sims_featureScheduler_runs1.7/twi_neo/
python /gscratch/scrubbed/yoachim/sims_featureScheduler_runs1.7/twi_neo/twilight_neo.py --night_pattern 2 --outDir /gscratch/scrubbed/yoachim/sims_featureScheduler_runs1.7/twi_neo/
python /gscratch/scrubbed/yoachim/sims_featureScheduler_runs1.7/twi_neo/twilight_neo.py --night_pattern 3 --outDir /gscratch/scrubbed/yoachim/sims_featureScheduler_runs1.7/twi_neo/
python /gscratch/scrubbed/yoachim/sims_featureScheduler_runs1.7/twi_neo/twilight_neo.py --night_pattern 4 --outDir /gscratch/scrubbed/yoachim/sims_featureScheduler_runs1.7/twi_neo/
python /gscratch/scrubbed/yoachim/sims_featureScheduler_runs1.7/twi_neo/twilight_neo.py --night_pattern 5 --outDir /gscratch/scrubbed/yoachim/sims_featureScheduler_runs1.7/twi_neo/
python /gscratch/scrubbed/yoachim/sims_featureScheduler_runs1.7/twi_neo/twilight_neo.py --night_pattern 6 --outDir /gscratch/scrubbed/yoachim/sims_featureScheduler_runs1.7/twi_neo/
python /gscratch/scrubbed/yoachim/sims_featureScheduler_runs1.7/twi_neo/twilight_neo.py --night_pattern 7 --outDir /gscratch/scrubbed/yoachim/sims_featureScheduler_runs1.7/twi_neo/
